version: 1

sources:
  swapi:
    kind: http
    config:
      url: https://swapi.dev/api

resources:
  sw_planets:
    cache_duration: 5s
    source: swapi
    params:
      method: get
      path: /planets

  sw_people:
    cache_duration: 10s
    source: swapi
    params:
      method: get
      path: /people

routes:
  - path: /v1/sw
    method: GET
    resources:
      sw_planets:
        as: planets
        output: "{results{name,population}}"
      sw_people:
        as: people
        output: "{results{name,height,mass,hair_color,skin_color,eye_color,birth_year}}"